### ISSUE TITLE
docker inspect postgres error

### ISSUE THREAD

**Issue by jgoodhcg** [jacobobryant/biff-postgres#1]
When I implemented the first commit on a fresh biff instance the `(shell {:out nil} "docker inspect postgres")` command threw an error and wouldn't proceed to pulling the image. I had to wrap it in a `try` to get past that command.

```
(defn start-postgres []
  (let [{:keys [exit]}
          (try
            (shell {:out :string, :err :string} "docker inspect postgres")
            (catch Exception _
              {:exit 1}))]
      (when (not= 0 exit)
        (shell "docker pull postgres")))
    (apply shell
           (concat ["docker" "run" "--rm"]
                   (:example/docker-postgres-args @config)
                   ["-v" (str (.getAbsolutePath (io/file "storage/postgres"))
                              ":/var/lib/postgresql/data")
                    "postgres"])))

```

**Comment by jacobobryant** [comment]
Thanks for the catch! I've updated the tutorial to point to [a new commit](https://github.com/jacobobryant/biff-postgres/commit/6e293ebbbee6d1f8128ea3b95514b46a4a315b93) which does this:

```clojure
  (try
    (shell {:out nil} "docker inspect postgres")
    (catch Exception e
      (shell "docker pull postgres")))
```

Let me know if you run into any other issues.
